server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    statusPageUrl: http://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: http://${eureka.instance.hostname}:${server.port}/health
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
          enabled: true

spring:
  application:
    name: eureka