server:
  port: 8091

eureka:
  #eueka 主机名
  instance:
    hostname: localhost
  client:
    #提供者和消费者的注册地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  application:
    name: provider
